[general]
import = [
  "/opt/homebrew/opt/tokyonight-extras/share/tokyonight-extras/alacritty/tokyonight_moon.toml",
  "~/.config/alacritty/keybindings/tmux.toml",
]

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux-detached"]

[env]
THEME = "tokyonight_moon"

[window]
dimensions = { columns = 120, lines = 40 }
padding = { x = 10, y = 10 }
decorations = "Buttonless"
resize_increments = true
option_as_alt = "Both"

[font]
normal.family = "BerkeleyMono Nerd Font Mono"

size = 19
