# XDG theorically implemented in vim 9.1
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')
set viminfofile=$XDG_STATE_HOME/vim/viminfo

set nocompatible
set ignorecase
set incsearch
set smartcase
set showmatch
set showcmd
set ruler

syntax on

set nobackup
set nowritebackup
set viminfo=
set textwidth=79
set tabstop=2
set shiftwidth=2
set cindent
set autoindent
set smarttab
set expandtab
set backspace=indent,eol,start

filetype on
filetype indent on
filetype plugin on

autocmd Filetype gitcommit set textwidth=68 spell

autocmd BufWritePre * :%s/\s\+$//e
