" Disable vi compat mode
set nocompatible

" Even with XDG compat, ~/.viminfo still gets written
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Write without backups
set nobackup
set nowritebackup
set noswapfile

" Improve search functionality
set ignorecase
set smartcase
set incsearch

" Show commands and cursor position in the status line
set showcmd
set ruler
set laststatus=2

" Set text formatting and indentation
set textwidth=79
set tabstop=4
set shiftwidth=4
set cindent
set autoindent
set smarttab
set backspace=indent,eol,start

syntax on

filetype on
filetype plugin on
filetype indent on

" git commit style
autocmd Filetype gitcommit set textwidth=68 spell

" Strip trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e
