# Taps
tap "homebrew/bundle"
tap "homebrew/services"
tap "josh/tap"

# Homebrew
brew "direnv"
brew "gh"
brew "git"
brew "gron"
brew "icu4c"
brew "jq"
brew "mas"
brew "node"
brew "ollama", restart_service: true
brew "openssl@1.1"
brew "python@3.11"
brew "prettier"
brew "pstree"
brew "pv"
brew "ripgrep"
brew "shellcheck"
brew "shfmt"
brew "swiftformat"
brew "swiftlint"
brew "terminal-notifier"
brew "watch"
brew "wget"
brew "josh/tap/bbedit-cli"
brew "josh/tap/itunes-library-export"

# Cask
cask "arc"
cask "firefox"
cask "logi-options-plus" if `ioreg -p IOUSB` =~ /USB Receiver/
cask "mimestream"
cask "raycast"
cask "secretive"
cask "sketch" if `system_profiler SPDisplaysDataType` =~ /Pro Display XDR/
cask "visual-studio-code"
