steps:
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: "github.com_ntotten"
      repositoryName: "$(Build.Repository.Name)"
      action: "create"
      target: "$(Build.SourceVersion)"
      tagSource: "gitTag"
      tagPattern: "v.*"
      releaseNotesInline: "See [CHANGE LOG](https://github.com/prettier/prettier-vscode/blob/master/CHANGELOG.md) for details."
      changeLogCompareToRelease: "lastFullRelease"
      changeLogType: "commitBased"
      assets: "$(Build.ArtifactStagingDirectory)"
