name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Install shfmt
        run: sudo snap install shfmt

      - name: ShellCheck files
        run: shellcheck $(bin/find-shebang sh .) $(bin/find-shebang bash .)

      - name: shfmt files
        run: shfmt -d $(bin/find-shebang sh .) $(bin/find-shebang bash .)

      - name: ShellCheck POSIX sh files
        run: shellcheck --shell=sh config/sh/*

      - name: shfmt POSIX sh files
        run: shfmt -ln posix -d config/sh/*

      - name: ShellCheck bash files
        run: shellcheck --shell=bash config/bash/*

      - name: shfmt bash files
        run: shfmt -ln bash -d config/bash/*

      - name: ShellCheck zsh files
        run: shellcheck --shell=bash config/zsh/*

      - name: shfmt zsh files
        run: shfmt -ln bash -d config/zsh/*
