name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Install shfmt
        run: sudo snap install shfmt

      - name: Install taplo
        run: |
          curl -fsSL https://github.com/tamasfe/taplo/releases/latest/download/taplo-full-linux-x86_64.gz | \
            gzip -d - | \
            install -m 755 /dev/stdin /usr/local/bin/taplo

      - name: ShellCheck files
        run: shellcheck $(local/bin/find-shebang sh .) $(local/bin/find-shebang bash .)

      - name: shfmt files
        run: shfmt -d $(local/bin/find-shebang sh .) $(local/bin/find-shebang bash .)

      - name: ShellCheck POSIX sh files
        run: shellcheck --shell=sh config/sh/*

      - name: shfmt POSIX sh files
        run: shfmt -ln posix -d config/sh/*

      - name: ShellCheck bash files
        run: shellcheck --shell=bash config/bash/* test/bash/*

      - name: shfmt bash files
        run: shfmt -ln bash -d config/bash/* test/bash/*

      - name: ShellCheck zsh files
        run: shellcheck --shell=bash config/zsh/* test/zsh/*

      - name: shfmt zsh files
        run: shfmt -ln bash -d config/zsh/* test/zsh/*
