name: ShellCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install ShellCheck
      run: apt-get install shellcheck

    - name: Check Bash files
      run: |
        shellcheck --shell=bash bash/*
