name: ShellCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install ShellCheck
      run: sudo apt-get install shellcheck

    - name: Check Bash files
      run: |
        shellcheck $(bin/find-shebang sh .) $(bin/find-shebang bash .)
        shellcheck --shell=bash bash/*
        shellcheck --shell=bash bash/*
        shellcheck --shell=bash zsh/*
