name: Shell

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Install shfmt
        run: sudo snap install shfmt

      - name: ShellCheck files
        run: shellcheck $(bin/find-shebang sh .) $(bin/find-shebang bash .)

      - name: ShellCheck POSIX sh files
        run: shellcheck --shell=sh sh/*

      - name: ShellCheck bash files
        run: shellcheck --shell=bash bash/*

      - name: ShellCheck zsh files
        run: shellcheck --shell=bash zsh/*
