name: Shell

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install ShellCheck
      run: sudo apt-get install shellcheck

    - name: Install shfmt
      run: sudo apt-get install shfmt

    - name: Check files
      run: shellcheck $(bin/find-shebang sh .) $(bin/find-shebang bash .)

    - name: Check POSIX sh files
      run: shellcheck --shell=sh sh/*

    - name: Check bash files
      run: shellcheck --shell=bash bash/*

    - name: Check zsh files
      run: shellcheck --shell=bash zsh/*
