name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dotfiles
        run: ./install.sh

      - name: ZSH Login / Interactive
        run: ./test/test-zsh-login-interactive.sh

      - name: ZSH Non-Login / Interactive
        run: ./test/test-zsh-nonlogin-interactive.sh
