name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install zsh
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: Ensure PATH directories exist
        run: |
          mkdir -p "$HOME/.local/bin"
          sudo mkdir -p "/usr/local/bin"
          sudo mkdir -p "/usr/local/sbin"

      - name: Install dotfiles
        run: ./install.sh

      - name: Bash version
        run: bash --version

      - name: Bash Login / Interactive
        run: |
          env -i HOME="$HOME" bash -l -i ./test/test-bash-login-interactive.sh

      - name: Bash Non-Login / Interactive
        run: |
          env -i HOME="$HOME" bash -i ./test/test-bash-nonlogin-interactive.sh

      - name: Bash Non-Interactive
        run: |
          env -i HOME="$HOME" bash ./test/test-bash-noninteractive.sh

      - name: ZSH version
        run: zsh --version

      - name: ZSH Login / Interactive
        run: |
          env -i HOME="$HOME" zsh -l -i ./test/test-zsh-login-interactive.sh

      - name: ZSH Non-Login / Interactive
        run: |
          env -i HOME="$HOME" zsh -i ./test/test-zsh-nonlogin-interactive.sh

      - name: ZSH Non-Interactive
        run: |
          env -i HOME="$HOME" zsh ./test/test-zsh-noninteractive.sh
