name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: Install dotfiles
        run: ./install.sh

      - name: ZSH Login / Interactive
        run: |
          env -i HOME="$HOME" zsh -l -i ./test/test-zsh-login-interactive.sh

      - name: ZSH Non-Login / Interactive
        run: |
          env -i HOME="$HOME" zsh -i ./test/test-zsh-nonlogin-interactive.sh

      - name: ZSH Non-Interactive
        run: |
          env -i HOME="$HOME" zsh ./test/test-zsh-noninteractive.sh
